### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-2-evaluacion-intermedia-Lourdesjupo#1]
Really cool job @Lourdesjupo  !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Enable Strict mode by writing `'use strict'` at the beginning of the js document.
- [x] Extract the feedback painter to a function.
- [x] In the reset function you can also clean the values ​​of the select and the input. 

### JavaScript: advanced

- [x] Check if the `<select>` has the default option (with no value).
- [x] Move the feedback logic to a function and execute it on each click.
- [x] Move your bet logic into a function and execute it on each click.
- [x] You are writing many times `"trackEl.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'trackEl'`?
- [x] Use `ev.preventDefault()` to prevent page reload.

### Good practices

- [x] Try to improve your commits messages. "Add JS" is a bit poor. "Add random number logic" is more explanatory.

### HTML

- [x] Add form

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Check if the player has enough money to bet and if the bet is greater than 0 and lower than the current amount of the player.
- Add a reset button that cleans the select, balance of money and writes the initial feedback. 
- Validates if the balance of money is available is less than the money bet and displays a message
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by Lourdesjupo** [comment]
Hi Yanelis thanks for your feedback!

I have finished all the points of the issue and improved some visual aspects, as well as logic. Let me know if I need to modify anything else.

thanks
